stop_words = set({"ourselves", "hers", "between", "yourself", "again",
				  "there", "about", "once", "during", "out", "very", "having",
				  "with", "they", "own", "an", "be", "some", "for", "do", "its",
				  "yours", "such", "into", "of", "most", "itself", "other",
				  "off", "is", "s", "am", "or", "who", "as", "from", "him",
				  "each", "the", "themselves", "below", "are", "we",
				  "these", "your", "his", "through", "don", "me", "were",
				  "her", "more", "himself", "this", "down", "should", "our",
				  "their", "while", "above", "both", "up", "to", "ours", "had",
				  "she", "all", "no", "when", "at", "any", "before", "them",
				  "same", "and", "been", "have", "in", "will", "on", "does",
				  "yourselves", "then", "that", "because", "what", "over",
				  "why", "so", "can", "did", "not", "now", "under", "he", "you",
				  "herself", "has", "just", "where", "too", "only", "myself",
				  "which", "those", "i", "after", "few", "whom", "t", "being",
				  "if", "theirs", "my", "against", "a", "by", "doing", "it",
				  "how", "further", "was", "here", "than"})

conjunctions = set({"and", "or", "but", "nor", "so", "for", "yet", "after", 
                    "although", "as", "as If", "as Long As", "because", 
                    "before", "even If", "even Though", "once", "since", 
                    "so that", "though", "till", "unless", "until", "what", 
                    "when", "whenever", "wherever", "whether", "while"})

# Natural Language Toolkit stop words - https://gist.github.com/sebleier/554280
NLTK_stop_words = set({"i", "me", "my", "myself", "we", "our", "ours", "ourselves", 
                  "you", "your", "yours", "yourself", "yourselves", "he", "him", 
                  "his", "himself", "she", "her", "hers", "herself", "it", "its", 
                  "itself", "they", "them", "their", "theirs", "themselves", "what", 
                  "which", "who", "whom", "this", "that", "these", "those", "am", 
                  "is", "are", "was", "were", "be", "been", "being", "have", "has", 
                  "had", "having", "do", "does", "did", "doing", "a", "an", "the", 
                  "and", "but", "if", "or", "because", "as", "until", "while", "of", 
                  "at", "by", "for", "with", "about", "against", "between", "into", 
                  "through", "during", "before", "after", "above", "below", "to", 
                  "from", "up", "down", "in", "out", "on", "off", "over", "under", 
                  "again", "further", "then", "once", "here", "there", "when", 
                  "where", "why", "how", "all", "any", "both", "each", "few", "more", 
                  "most", "other", "some", "such", "no", "nor", "not", "only", "own", 
                  "same", "so", "than", "too", "very", "s", "t", "can", "will", "just", 
                  "don", "should", "now", "d", "ll", "m", "o", "re", "ve", "y", "ain", 
                  "aren", "arent", "couldn", "couldnt", "didn", "didnt", "doesn", 
                  "doesnt", "hadn", "hadnt", "hasn", "hasnt", "haven", "havent", 
                  "isn", "isnt", "ma", "mightn", "mightnt", "mustn", "mustnt", 
                  "needn", "neednt", "shan", "shant", "shouldn", "shouldnt", "wasn", 
                  "wasnt", "weren", "werent", "won", "wont", "wouldn", "wouldnt"})